<div>
    An error occurred while invoking API for {{data['acc_number']}}<br/>
		<br>AWS Lambda function: <b>{{data['function_name']}}</b>
        <br>Cloudwatch Logs: <b>{{data['log_file']}}</b>
        <br>Event obtained by Lambda: <pre>{{ data['event'] | pprint }}</pre>
		<br><br>
</div>
<div>
    The traceback for the error:<br/>
    <p><pre style="color:maroon">{{data['error']}}</pre></p> <br>
</div>
